version: '3.8'
services:
  db:
    container_name: db_postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fiber-rest
    ports:
        - '5432:5432'
